title: Sajith Herath
subtitle: Tech Enthusiast, Traveller
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://sajiya.dev" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: About Me
    url: /about
  - text: Blog
    url: /blog
  - text: Photography
    url: /photography
  - text: Videography
    url: /videography
  #    - text: Shop
  #      url : /shop
  - text: Contact Me
    url: /contact

# Edit these details

author_logo: sajith.jpg
author: Sajith Herath
author_bio: Software Engineer
author_description: >-
  Highly skilled and enthusiastic software engineer with 2+ years of work experience in innovative application design
  and development. Skilled in research and development, backend, machine learning, object-oriented and functional
  programming, devops, and agile process.<br><br>

  In my free time, I travel and do photographyðŸ“· in nature, wildlife
  and landscapes. Check GalleryðŸ˜‰. Finally, I love hang with friends.
author_email: "sajithdherath@gmail.com"
author_location: Sri Lanka
author_website_url: "http://sajiya.dev/"

author_timeline:
  - "2021 - Present: Senior Software Engineer: PrimeSens LLC"
  - "2020 - 2021: Freelance Software Engineer"
  - "2019 - 2020: Software Engineer in Machine Learning: Arimac Lanka<br>"
  - "2017 - 2018: Intern on Software Engineering: Fortunaglobal (Pvt) Limited<br>"
  - "2015 - 2019: Informatics Institute of Technology (IIT-Sri Lanka) affiliated with University of Westminster:
              BEng in Software Engineering<br>"


# social links
twitter_username: sajithdherath
github_username: sajithdherath
facebook_username: sajith.deshapriya
linkedin_username: sajith-herath
instagram_username: sajith_deshappriya
medium_username: sajithdherath
stackoverflow_username: 7764309/sajith-herath

#for comments using disqus
disqus_shortname: http-sajithdherath-github-io

# wakatime username (coding activity)
wakatime_username:

# mailchimp embedded form url (newsletter):
mailchimp_form_url:

# formspree (contact form)
formspree_email: sajithdherath@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-93971208-2

# Choose what to show ( can be true or false)
show_author_timeline: true
show_author_project_details: true

# algolia search
algolia:
  application_id: KJLONE9A5L
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: [ ]
  nodes_to_index: 'article'
  search_only_api_key: 982a04f5cb2c52827bed0b44f5aeedcd

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
  - products

# Gallery
defaults:
  - scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
